---
- name: postgres_exporter 다운로드
  get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v0.15.0/postgres_exporter-0.15.0.linux-amd64.tar.gz"
    dest: "/tmp/postgres_exporter.tar.gz"
    mode: "0644"

- name: postgres_exporter 압축 해제
  unarchive:
    src: "/tmp/postgres_exporter.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: postgres_exporter 바이너리 이동
  copy:
    src: "/tmp/postgres_exporter-0.15.0.linux-amd64/postgres_exporter"
    dest: "/usr/local/bin/postgres_exporter"
    owner: root
    group: root
    mode: "0755"
    remote_src: yes

- name: postgres_exporter 사용자 생성
  user:
    name: postgres_exporter
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: postgres_exporter systemd 서비스 파일 생성
  copy:
    dest: "/etc/systemd/system/postgres_exporter.service"
    mode: "0644"
    content: |
      [Unit]
      Description=Prometheus PostgreSQL Exporter
      After=network.target

      [Service]
      User=postgres_exporter
      Group=postgres_exporter
      Type=simple
      Environment="DATA_SOURCE_NAME=postgresql://{{ db_user }}:{{ db_pass }}@localhost:5432/{{ db_name }}?sslmode=disable"
      ExecStart=/usr/local/bin/postgres_exporter

      [Install]
      WantedBy=multi-user.target

  notify: restart_postgres_exporter

- name: postgres_exporter 서비스 활성화 및 시작
  systemd:
    name: postgres_exporter
    enabled: yes
    state: started
    daemon_reload: yes