---
app_user: adreamin

app_root: /home/adreamin/web/fastapi/event_service

app_dir: "{{ app_root }}/app"

venv_dir: "{{ app_root }}/venv"

log_dir: "{{ app_root }}/logs"

service_name: event_service

local_app_path: "{{ playbook_dir }}/../../web/event_service"