app_user: ec2-user

app_root: /home/ec2-user/web/fastapi/event_service

app_dir: "{{ app_root }}/app"

venv_dir: "{{ app_root }}/venv"

log_dir: "{{ app_root }}/logs"

service_name: event_service

local_app_path: "{{ playbook_dir }}/../../web/event_service"