---
- name: "Node Exporter 패키지 다운로드"
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"


- name: "압축 풀기"
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes


- name: "실행 파일 이동 및 권한 설정"
  copy:
    src: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    remote_src: yes


- name: "Node Exporter 서비스 등록 (Systemd)"
  copy:
    dest: "/etc/systemd/system/node_exporter.service"
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=root
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: "서비스 시작 및 활성화"
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes # 서비스 파일이 바뀌었을 때를 대비해 리로드 추가
