"all":
  "children":
    "bastion":
      "hosts":
        "bastion01":
          "ansible_host": "54.180.229.112"
          "ansible_ssh_private_key_file": "~/.ssh/bastion-key.pem"
    "db":
      "hosts":
        "db01":
          "ansible_host": "10.0.30.11"
          "ansible_ssh_common_args": |
            -o ProxyCommand="ssh -i ~/.ssh/bastion-key.pem -W %h:%p -q adreamin@54.180.229.112"
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
    "was":
      "hosts":
        "was01":
          "ansible_host": "10.0.10.144"
          "ansible_ssh_common_args": |
            -o ProxyCommand="ssh -i ~/.ssh/bastion-key.pem -W %h:%p -q adreamin@54.180.229.112"
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
  "vars":
    "ansible_host_key_checking": false
    "ansible_ssh_private_key_file": "~/.ssh/ansible-key.pem"
    "ansible_user": "adreamin"
