---

#ansible-playbook -i inventories/bootstrap/inventory.yml playbooks/bootstrap.yml
#ansible-playbook -i inventories/dev/inventory.yml playbooks/site.yml

- name: Bastion setup
  hosts: bastion
  remote_user: adreamin
  become: yes

  roles:
    - monitoring_grafana
    - monitoring_prometheus

- name: WAS setup
  hosts: was
  remote_user: adreamin
  become: yes

  roles:
    - nginx
    - fastapi
    - node_exporters

- name: DB setup
  hosts: db
  remote_user: adreamin
  become: yes

  roles:
    - postgresql
    - node_exporters
    - postgres_exporters