# 변수화 하기전 코드
# ---
# - name: Install packages
#   dnf:
#     name:
#       - python3-pip
#       - rsync
#     state: present

# - name: Create app directory
#   file:
#     path: /home/adreamin/web/fastapi/event_service
#     state: directory
#     owner: adreamin
#     group: adreamin
#     mode: '0755'
#     #recurse: yes

# - name: Allow nginx to access app home 
#   file: 
#     path: /home/adreamin 
#     state: directory 
#     owner: adreamin 
#     group: adreamin 
#     mode: '0755'

# - name: Deploy FastAPI source
#   copy:
#     src: "{{ playbook_dir }}/../../web/event_service/deploy/"
#     dest: /home/adreamin/web/fastapi/event_service/
#     owner: adreamin
#     group: adreamin
#     mode: '0644'
#     directory_mode: '0755'
#   become: false
#   register: app_copy

# - name: Create virtual environment
#   command:
#     cmd: python3 -m venv /home/adreamin/web/fastapi/event_service/venv
#     creates: /home/adreamin/web/fastapi/event_service/venv/bin/activate
#   register: venv_created

# - name: Upgrade pip
#   pip:
#     name: pip
#     state: latest
#     virtualenv: /home/adreamin/web/fastapi/event_service/venv
#   when: venv_created.changed

# - name: Install python packages
#   pip:
#     requirements: /home/adreamin/web/fastapi/event_service/requirements.txt
#     virtualenv: /home/adreamin/web/fastapi/event_service/venv
#   when: venv_created.changed


# - name: Check FastAPI process
#   shell: pgrep -f "uvicorn main:app"
#   register: fastapi_pid
#   ignore_errors: yes
#   changed_when: false

# - name: Stop FastAPI if running
#   shell: pkill -f "uvicorn main:app"
#   when: fastapi_pid.rc == 0
#   ignore_errors: yes

# - name: Run FastAPI server
#   shell: |
#     nohup /home/adreamin/web/fastapi/event_service/venv/bin/uvicorn main:app \
#       --host 0.0.0.0 \
#       --port 8000 \
#       > /home/adreamin/web/fastapi/event_service/server.log 2>&1 &
#   args:
#     chdir: /home/adreamin/web/fastapi/event_service

---
- name: Install packages
  dnf:
    name:
      - python3-pip
      - rsync
    state: present

- name: Create app directory
  file:
    path: "{{ app_root }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

- name: Allow nginx to access app home
  file:
    path: "/home/{{ app_user }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

- name: Deploy FastAPI source
  copy:
    src: "{{ local_app_path }}/deploy/"
    dest: "{{ app_root }}/"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'
    directory_mode: '0755'
  become: false
  register: app_copy

- name: Create virtual environment
  command:
    cmd: "python3 -m venv {{ venv_dir }}"
    creates: "{{ venv_dir }}/bin/activate"
  register: venv_created

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ venv_dir }}"
  when: venv_created.changed

- name: Install python packages
  pip:
    requirements: "{{ app_root }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"
  when: venv_created.changed

- name: Check FastAPI process
  shell: pgrep -f "uvicorn main:app"
  register: fastapi_pid
  ignore_errors: yes
  changed_when: false

- name: Stop FastAPI if running
  shell: pkill -f "uvicorn main:app"
  when: fastapi_pid.rc == 0
  ignore_errors: yes

- name: Run FastAPI server
  shell: |
    nohup {{ venv_dir }}/bin/uvicorn main:app \
      --host 0.0.0.0 \
      --port 8000 \
      > {{ app_root }}/server.log 2>&1 &
  args:
    chdir: "{{ app_root }}"


# - name: Create systemd service
#   template:
#     src: event_service.service.j2
#     dest: /etc/systemd/system/event_service.service

# - name: Reload systemd
#   systemd:
#     daemon_reload: yes

# - name: Start FastAPI service
#   systemd:
#     name: event_service
#     enabled: yes
#     state: restarted