---
- name: "이벤트 계정 생성 & DB 생성"
  become: yes
  shell: |
    sudo -u postgres psql <<'EOF'

    DO
    $$
    BEGIN
      IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles
        WHERE rolname = '{{ event_user }}'
      ) THEN
        CREATE USER {{ event_user }} WITH PASSWORD '{{ event_pass }}';
      END IF;
    END
    $$;

    SELECT 'CREATE DATABASE {{ event_db }} OWNER {{ event_user }}'
    WHERE NOT EXISTS (
      SELECT FROM pg_database
      WHERE datname = '{{ event_db }}'
    )\gexec

    GRANT ALL PRIVILEGES ON DATABASE {{ event_db }} TO {{ event_user }};

    EOF
  args:
    executable: /bin/bash

- name: "public schema owner 변경"
  become: yes
  shell: >
    sudo -u postgres psql -d {{ event_db }}
    -c "ALTER SCHEMA public OWNER TO {{ event_user }};"
  args:
    executable: /bin/bash

- name: "schema 권한 부여"
  become: yes
  shell: >
    sudo -u postgres psql -d {{ event_db }}
    -c "GRANT USAGE, CREATE ON SCHEMA public TO {{ event_user }};"
  args:
    executable: /bin/bash

- name: "table 권한 부여"
  become: yes
  shell: >
    sudo -u postgres psql -d {{ event_db }}
    -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{ event_user }};"
  args:
    executable: /bin/bash

- name: "sequence 권한 부여"
  become: yes
  shell: >
    sudo -u postgres psql -d {{ event_db }}
    -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO {{ event_user }};"
  args:
    executable: /bin/bash

- name: "default table privilege"
  become: yes
  shell: >
    sudo -u postgres psql -d {{ event_db }}
    -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL PRIVILEGES ON TABLES TO {{ event_user }};"
  args:
    executable: /bin/bash

- name: "default sequence privilege"
  become: yes
  shell: >
    sudo -u postgres psql -d {{ event_db }}
    -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL PRIVILEGES ON SEQUENCES TO {{ event_user }};"
  args:
    executable: /bin/bash

    
- name: "초기 sql데이터 주입"
  copy:
    src: ../files/eventdb.sql
    dest: /tmp/eventdb.sql
    owner: postgres
    group: postgres
    mode: "0644"

- name: "event table생성"
  shell: |
    sudo -u postgres psql -d {{ event_db }} -f /tmp/eventdb.sql



# #Ansible postgresql modules
# - name: Create user
#   community.postgresql.postgresql_user:
#     name: "{{ event_user }}"
#     password: "{{ event_pass }}"
#     state: present

# - name: Create DB
#   community.postgresql.postgresql_db:
#     name: "{{ event_db }}"
#     owner: "{{ event_user }}"
#     state: present

# - name: Grant privileges
#   community.postgresql.postgresql_privs:
#     db: "{{ event_db }}"
#     role: "{{ event_user }}"
#     type: database
#     privs: ALL