name: "Packer AMI"
on:
  push:
    branches:
      - main
    paths:
      - "packer/**" # packer/ 하위경로에 변화가 있을때 동작하게 한다.
jobs:
  packer_build:
    runs-on: ubuntu-latest
    name: "Build AMI with packer & ansible"
    steps:
      - name: Checkout Repository # github 저장소로 부터 소스코드 가져오기
        uses: actions/checkout@v4


      - name: Setup Packer # ubuntu 에 packer 설치
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"
